/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atmpin;

import basic.ATMDB;
import operation.GetBalance;
import basic.ProcessingPage;
import basic.TransactionStatus;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author HARSHIT
 */
public class ATMPin extends javax.swing.JFrame {
    ATMDB db;
    String accno;
    int amount;
    
    /**
     * Creates new form ATMWithdraw
     */
    public ATMPin(String acc,int amt) {
        initComponents();
        accno = acc;
        amount = amt;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        atmPinPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        atmPinPanel.setBackground(new java.awt.Color(188, 253, 255));
        atmPinPanel.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Please Enter Your  4 digit Pin");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        pass.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pass.setBorder(null);

        javax.swing.GroupLayout atmPinPanelLayout = new javax.swing.GroupLayout(atmPinPanel);
        atmPinPanel.setLayout(atmPinPanelLayout);
        atmPinPanelLayout.setHorizontalGroup(
            atmPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(atmPinPanelLayout.createSequentialGroup()
                .addGroup(atmPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(atmPinPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, atmPinPanelLayout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addComponent(jButton2)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        atmPinPanelLayout.setVerticalGroup(
            atmPinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(atmPinPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel4)
                .addGap(83, 83, 83)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(jButton2)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(atmPinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(atmPinPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int accbal = GetBalance.balance(accno);
        if(amount<=accbal){
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd"); 
            LocalDateTime ldate = LocalDateTime.now();
            LocalTime ltime = LocalTime.now();
            String date = (dtf.format(ldate));
            String time = ltime.getHour()+":"+ltime.getMinute()+":"+ltime.getSecond();
            
            int pin = Integer.parseInt(pass.getText());
            db = new ATMDB();
            try
            {  
                db.rs = db.stm.executeQuery("SELECT * FROM `atmcarddetails` WHERE `AccNo`= "+accno+" AND `ATMCardPin`= "+pin+";");
                if(db.rs.next()){
                    if(amount == 0){
                        this.setVisible(false);
                        TransactionStatus ts = new TransactionStatus("Account Balance: ","Rs "+accbal,"");
                        ts.setVisible(true); 
                    }else{
                        String query = "INSERT INTO `withdrawdetails`(`AccNo`, `WithdrawAmount`, `AtmPinVerified`, `WithdrawDate`, `WithdrawTime`) VALUES ('"+accno+"','"+amount+"','1','"+date+"','"+time+"');";
                        //System.out.println(query);
                        db.pst = db.con.prepareStatement(query);
                        db.pst.executeUpdate();
                        
                        query = "SELECT `TransactionID` FROM `withdrawdetails` WHERE `AccNo`='"+accno+"' AND `WithdrawTime`='"+time+"' AND `WithdrawDate`='"+date+"'";
                        //System.out.println(query);
                        db.rs = db.stm.executeQuery(query);
                        db.rs.next();
                        int tranid = db.rs.getInt("TransactionID");
                        ProcessingPage p = new ProcessingPage(accno,tranid);
                        p.setVisible(true);
                        this.setVisible(false);  
                    }
                }else{
                    this.setVisible(false);
                    TransactionStatus ts = new TransactionStatus("Transaction Declined ...","Entered PIN is Wrong !!! ","Please Contact Your Bank / Try Again");
                    ts.setVisible(true); 
                }
            }catch(Exception e){
                System.out.println(e); 
            }
        }else{
           this.setVisible(false);
           TransactionStatus ts = new TransactionStatus("Invalid Amount...","Sorry For Inconvinience !!!","Please Contact Your Bank / Try Again "); 
           ts.setVisible(true);
        }  
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATMPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATMPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATMPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATMPin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String a = null;
                int b = 0;
                new ATMPin(a,b).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atmPinPanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
